name: Quarkus CI/CD

on:
  push:
    branches:
      - develop

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build and Test Quarkus Project
        run: |
          ./gradlew clean build -x test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Install OpenSSL Libraries
        run: sudo apt-get install -y libssl-dev

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""

      - name: Add SSH Key to SSH Agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

#      - name: Deploy to GitHub Pages
#        run: |
#          # Assuming your Quarkus project generates static files in the `build` directory
#          ./gradlew quarkusBuild
#          mkdir -p deploy
#          cp -r build/* deploy/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./deploy