name: Quarkus CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build and Test Quarkus Project
        run: |
          ./mvnw clean verify

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Deploy to GitHub Pages
        run: |
          ./mvnw clean package -DskipTests
          mkdir -p deploy
          cp target/*-runner.jar deploy/application.jar

      - name: Deploy to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: deploy/*
          tag_name: ${{ github.sha }}
          title: Release ${{ github.sha }}