name: Quarkus CI/CD

on:
  push:
    branches:
      - main

permissions: read-all|write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build and Test Quarkus Project
        run: |
          ./gradlew clean build -x test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Deploy to GitHub Pages
        run: |
          # Assuming your Quarkus project generates static files in the `build` directory
          ./gradlew quarkusBuild
          mkdir -p deploy
          cp -r build/* deploy/

      - name: Deploy to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: deploy/*
          tag_name: ${{ github.sha }}
          title: Release ${{ github.sha }}